1. Take three float values in three variables by user input and find out the sum of three values.

In [ ]:
#taking 3 inputs
val1=float(input("Enter value 1: "))
val2=float(input("Enter value 2: "))
val3=float(input("Enter value 3: "))

sum=val1+val2+val3
print("Sum is :",sum)


Enter value 1: 2.36
Enter value 2: 7.96
Enter value 3: 4.65
Sum is : 14.97


2. Take three lists, print them and find out the sum of three lists

In [ ]:
n=3
a=[int(input()) for i in range(n)]
b=[int(input()) for i in range(n)]
c=[int(input()) for i in range(n)]

print("Lists are : ", a, b, c)

totalSum=sum(a)+sum(b)+sum(c)
print("Sum of 3 list is :", totalSum)

1
2
3
4
5
6
9
8
7
Lists are :  [1, 2, 3] [4, 5, 6] [9, 8, 7]
Sum of 3 list is : 45


3. Print the sum of first 100 numbers using for loop, while loop and do while loop

In [ ]:
#using for loop
sum=0
for i in range(1, 101):
  sum+=i
print(sum)

#using while loop
sum=0
i=1
while i<101:
  sum+=i
  i+=1

print(sum)

#using do while
sum=0
i=1
while True:
  sum+=i
  i+=1
  if i>100:
    break

print(sum)

5050
5050
5050


4. Print the Fibonacci series using for loop

In [ ]:
def print_fibonacchi(n):
  a, b=0,1
  print("Fibonacchi Series:")
  for _ in range(n):
    print(a, end=" ")
    a,b = b, a+b



nums=10
print_fibonacchi(nums)

Fibonacchi Series:
0 1 1 2 3 5 8 13 21 34 

5. Take three strings as user input, print them and concatenate them.

In [ ]:
str1=input("Enter string1: ")
str2=input("Enter string2: ")
str3=input("Enter string3: ")

print(str1)
print(str2)
print(str3)

concat=str1+str2+str3
print(concat)

Enter string1: Md Fahim 
Enter string2: Bin 
Enter string3: Alam
Md Fahim 
Bin 
Alam
Md Fahim Bin Alam


6. Perform String slicing operation: Slice from the start, slice to the end and slicing using Negative indexing.

In [ ]:
smplStr= "Md Fahim Bin Alam"

#slice from start
slice_start=smplStr[:8]
print("Slice start: ", slice_start)

slice_end=smplStr[13: ]
print("Slice end: ", slice_end)

slice_neg_idx=smplStr[-14: -5]
print("Slice negative indexing: ", slice_neg_idx)

Slice start:  Md Fahim
Slice end:  Alam
Slice negative indexing:  Fahim Bin


7. Determine the grade of a student using if..else logic if subject number is taken as userinput

In [ ]:
def calculate_grade():
  n=int(input("Enter the number of subjects: "))
  totalMarks=0

  for i in range(n):
    marks=float(input(f"Enter marks for the subject {i+1}: "))
    totalMarks+=marks

  averageMarks=totalMarks/n

  if averageMarks>=90:
    grade="A"
  elif averageMarks>=75:
    grade="B"
  elif averageMarks>=60:
    grade="C"
  elif averageMarks>=50:
    grade="D"
  else:
    grade="F"

  print(f"Average marks: {averageMarks}")
  print(f"Grade: {grade}")

calculate_grade()

Enter the number of subjects: 3
Enter marks for the subject 1: 95
Enter marks for the subject 2: 96
Enter marks for the subject 3: 99
Average marks: 96.66666666666667
Grade: A


8. Determine the grade of a student using switch..case logic if subject number is taken as user input.

In [ ]:
def get_grade(average):
  grade={
      (90, 100):'A+',
      (80, 89):'A',
      (70, 79):'B+',
      (60, 69):'B',
      (50, 59):'C+',
      (40, 49):'C',
      (30, 39):'D',
      (0, 29):'F'
  }

  for tup, i in grade.items():
    if tup[0]<=average<=tup[1]:
      return i
  return "Invalid Marks"

def main():
  n=int(input("Enter the number of subjects: "))
  total_marks=0
  for i in range(n):
    marks=float(input(f"Enter marks for subjects {i+1}: "))
    total_marks+=marks

  average=total_marks/n

  print(f"The avg marks : {average}")

  grade=get_grade(average)
  print(f"Grade is : {grade}")

main()

Enter the number of subjects: 3
Enter marks for subjects 1: 90
Enter marks for subjects 2: 89
Enter marks for subjects 3: 95
The avg marks : 91.33333333333333
Grade is : A+


9. Take four NumPy arrays (nparray1, nparray2, nparray3, nparray4). Define nparray1=[[1,2,3,4], [5,6,7,8]]), nparray2=[5,6,7,8], nparray3 as zeros of dimension (3,4) and nparray4 as ones of dimension (3,7). Now perform NumPy array slicing: selecting 1st 2 rows and 1st two colums, first element, middle element, and last element individually.

In [3]:
import numpy as np

nparray1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
nparray2 = np.array([5, 6, 7, 8])
nparray3 = np.zeros((3, 4))
nparray4 = np.ones((3, 7))

#perform slicing and display the results

print("nparray1: ")
print(nparray1)
print("Selecting 1st 2 rows and 1st 2 colums: ")
print(nparray1[:2, :2])
print("First element: ")
print(nparray1[0,0])
print("Middle element: ")
print(nparray1[0, len(nparray1[0])//2])
print("Last element: ")
print(nparray1[-1,-1])

print("\nnparray2: ")
print(nparray2)
print("Selecting 1st two elements: ")
print(nparray2[:2])
print("First element: ")
print(nparray2[0])
print("Middle element: ")
print(nparray2[len(nparray2)//2])
print("Last element: ")
print(nparray2[-1])


print("\nnparray3: ")
print(nparray3)
print("Selecting 1st 2rows and 1st two colums: ")
print(nparray3[:2, :2])
print("First element: ")
print(nparray3[0,0])
print("Middle element: ")
print(nparray3[1, len(nparray3[1])//2])
print("Last element: ")
print(nparray3[-1, -1])


print("\nnparray4: ")
print(nparray4)
print("Selecting 1st 2 rows and 1st 2 columns: ")
print(nparray4[:2, :2])
print("First element: ")
print(nparray4[0, 0])
print("Middle element: ")
print(nparray4[1, len(nparray4[1])//2])
print("Last element: ")
print(nparray4[-1,-1])


nparray1: 
[[1 2 3 4]
 [5 6 7 8]]
Selecting 1st 2 rows and 1st 2 colums: 
[[1 2]
 [5 6]]
First element: 
1
Middle element: 
3
Last element: 
8

nparray2: 
[5 6 7 8]
Selecting 1st two elements: 
[5 6]
First element: 
5
Middle element: 
7
Last element: 
8

nparray3: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Selecting 1st 2rows and 1st two colums: 
[[0. 0.]
 [0. 0.]]
First element: 
0.0
Middle element: 
0.0
Last element: 
0.0

nparray4: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
Selecting 1st 2 rows and 1st 2 columns: 
[[1. 1.]
 [1. 1.]]
First element: 
1.0
Middle element: 
1.0
Last element: 
1.0


Evaluation

In [13]:
#1
first=input("Enter first name: ")
middle=input("Enter middle name: ")
last=input("Enter last name: ")

name=first+middle+last

#2
math=float(input("\nEnter marks of math: "))
phy=float(input("Enter marks of physica: "))
eng=float(input("Enter marks of english: "))

#3
#using for loop
sum=0
for i in range(1, 101):
  sum+=i
print(sum)

#using while loop
sum=0
i=1
while i<101:
  sum+=i
  i+=1

print(sum)

#using do while
sum=0
i=1
while True:
  sum+=i
  i+=1
  if i>100:
    break

print(sum)


#4

def print_fibonacchi(n):
  a, b=0,1
  print("\nFibonacchi Series:")
  for _ in range(n):
    print(a, end=" ")
    a,b = b, a+b

nums=10
print_fibonacchi(nums)

#5
print("\nFirst 5 char: ", name[:5])
print("End 5 char: ", name[-5:])
print("last 3 char: ", name[-3:])


#6
subName=input("\nEnter subject name: ")
m=0
if(subName=='math'):
  m=math
elif(subName=='phy'):
  m=phy
elif(subName=='eng'):
  m=eng

if (m>=80 and m<=100):
  grade='A+'
elif(m>=70 and m<80):
  grade='A'
elif(m>=60 and m<70):
  grade='A-'
elif(m>=50 and m<60):
  grade='B'
else:
  grade='F'

print(f"Grade is : {grade}")

#7

list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]

print(list1)
print(list2)
print(list3)


import numpy as np

arr1=np.array(list1)
arr2=np.array(list2)
arr3=np.array(list3)

sum_arr=arr1+arr2+arr3

print(sum_arr)

#8

nparray1=np.array([[1,2,3,4], [5,6,7,8]])
nparray2=np.array([5,6,7,8])
nparray3=np.zeros((3,4))
nparray4=np.ones((3,7))

print("\nFirst 2rows and first 2 colums of nparray1: ")
print(nparray1[:2,:2])

def print_element(name, arr):
  flat=arr.flatten()
  first=flat[0]
  middle=flat[len(flat)//2]
  last=flat[-1]

  print(f"\n{name}: ")
  print("First: ", first)
  print("Middle: ", middle)
  print("Last: ", last)


print("First element, middle element, and last element: ")
print_element(nparray2, nparray2)
print_element(nparray3, nparray3)
print_element(nparray4, nparray4)



Enter first name: Md Fahim 
Enter middle name: Bin 
Enter last name: Alam

Enter marks of math: 98
Enter marks of physica: 97
Enter marks of english: 99
5050
5050
5050

Fibonacchi Series:
0 1 1 2 3 5 8 13 21 34 
First 5 char:  Md Fa
End 5 char:   Alam
last 3 char:  lam

Enter subject name: eng
Grade is : A+
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[12 15 18]

First 2rows and first 2 colums of nparray1: 
[[1 2]
 [5 6]]
First element, middle element, and last element: 

[5 6 7 8]: 
First:  5
Middle:  7
Last:  8

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]: 
First:  0.0
Middle:  0.0
Last:  0.0

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]: 
First:  1.0
Middle:  1.0
Last:  1.0
